### ISSUE TITLE
object has no method "debuglog"

### ISSUE THREAD

**Issue by brianehlert** [shashiu/ews-client#1]
brian@BrianEhUbu:~/meshblu-exchange$ node command.js

/home/brian/meshblu-exchange/node_modules/ews/node_modules/agentkeepalive/lib/agent.js:22
var debug = util.debuglog('http');
                 ^
TypeError: Object #<Object> has no method 'debuglog'
    at Object.<anonymous> (/home/brian/meshblu-exchange/node_modules/ews/node_modules/agentkeepalive/lib/agent.js:22:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/brian/meshblu-exchange/node_modules/ews/node_modules/agentkeepalive/index.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
brian@BrianEhUbu:~/meshblu-exchange$ 
brian@BrianEhUbu:~/meshblu-exchange$ node command.js

/home/brian/meshblu-exchange/node_modules/ews/node_modules/agentkeepalive/lib/agent.js:22
var debug = util.debuglog('http');
                 ^
TypeError: Object #<Object> has no method 'debuglog'
    at Object.<anonymous> (/home/brian/meshblu-exchange/node_modules/ews/node_modules/agentkeepalive/lib/agent.js:22:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/brian/meshblu-exchange/node_modules/ews/node_modules/agentkeepalive/index.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
brian@BrianEhUbu:~/meshblu-exchange$

**Comment by brianehlert** [comment]
Okay.
That particular error is due to an old version of Node.
